### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by AlexCoul**
"and identiied" --> "to identify"

This pull request is the occasion to ask whether it's ok for you all if we say the aggregation is done by computing only the average and not the standard deviation of gene expression. The main idea is here (looking at neighbors), but there is this std lacking whereas it's important for the analyzes, but we also have to keep it short so I'm totally ok with it.

### CODE REVIEW

**Review by cgreene — APPROVED** [review]

**Comment by kimanh-lecao** [comment]
@AlexCoul do you want to add one sentence here? The aim is really to highlight the lack of appropriate tools.

**Comment by kimanh-lecao** [comment]
@AlexCoul do you want to add one sentence here? The aim is really to highlight the lack of appropriate tools.

**Comment by kimanh-lecao** [comment]
@AlexCoul do you want to add one sentence here? The aim is really to highlight the lack of appropriate tools.

**Comment by kimanh-lecao** [comment]
@AlexCoul do you want to add one sentence here? The aim is really to highlight the lack of appropriate tools.

**Pull request merged**
