### PR TITLE
Create 80.glossary.md

### PR DESCRIPTION
**Pull request by cgreene**
I'm creating a stub for the glossary here.

### CODE REVIEW

**Comment by AlexCoul** [comment]
Great! Shall we also fill in synonyms and motive our common choice of a particular word instead all others?

**Comment by singha53-zz** [comment]
@AlexCoul  I was thinking of that too; something like this. we should agree on a format otherwise there may be merge conflicts lol
Screen Shot 2020-06-19 at 11 43 42 AM

**Comment by AlexCoul** [comment]
> @AlexCoul I was thinking of that too; something like this. we should agree on a format otherwise there may be merge conflicts lol
> Screen Shot 2020-06-19 at 11 43 42 AM

Yes that looks like a good solution :)

**Comment by cgreene** [comment]
I like the table idea! Would one of you file a pull request to convert the bulleted list to the header and first line of a table with an example? Thanks!

**Pull request merged**
